apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trainings.tektutor.org 
spec:
  group: tektutor.org 
  versions:
    - name: v1
      served: true 
      storage: false 
      schema:
        openAPIV3Schema:
          type: object
          properties:
            training:
               type: string
            duration:
               type: string
          required:
            - training
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            training:
               type: string
            duration:
               type: string
            city:
               type: string
            from:
               type: string
            to:
               type: string
  conversion:
    strategy: None
  scope: Namespaced
  names:
    kind: Training 
    listKind: TrainingList
    plural: trainings 
    singular: training 
    shortNames:
    - train 
