apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clean-target-dir
spec:
  workspaces:
     - name: output 
       mountPath: /workspace
  steps:
     - name: print
       image: ubuntu
       command:
         - echo
       args:
         - "$(workspaces.output.path)/source/target"

     - name: cleanup 
       image: ubuntu
       command:
         - rm 
       args:
         - -rf
         - "$(workspaces.output.path)/source/target"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
   name: delete-taskrun
spec:
   taskRef:
     name: clean-target-dir 
   workspaces:
      - name: output 
        persistentVolumeClaim:
          claimName: maven-tekton-pvc
