apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-tekton-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mnt/nfs_share 
    server: 192.168.1.80 
