apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clean-target-dir
spec:
  workspaces:
     - name: output 
       mountPath: /workspace
  steps:
     - name: print
       image: ubuntu
       command:
         - echo
       args:
         - "$(workspaces.output.path)/source/target"

     - name: cleanup 
       image: ubuntu
       script: | 
           if [ -d "$(workspaces.output.path)/source/target" ]; then 
               rm -rf "$(workspaces.output.path)/source/target"
           fi
---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-tekton-pipeline-cached
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-repo 
    - name: local-repo 
  tasks:
    - name: cleanup-target-folder
      taskRef:
        name: clean-target-dir 
      workspaces:
        - name: output 
          workspace: shared-workspace

    - name: clone-github-repo 
      taskRef:
        name: git-clone
      runAfter:
        - cleanup-target-folder 
      workspaces:
        - name: output 
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/tektutor/spring-ms.git
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "master"

    - name: start-maven-build 
      taskRef:
        name: maven
      runAfter:
        - clone-github-repo 
      params:
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -DskipTests
            - -Dmaven.repo.local="$(workspaces.local-repo.path)/m2"
            - clean
            - package
            - -X
      workspaces:
        - name: maven-settings 
          workspace: maven-repo
        - name: m2
          workspace: local-repo
        - name: source 
          workspace: shared-workspace
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-tekton-pipeline-cached-run
spec:
  pipelineRef:
    name: maven-tekton-pipeline-cached
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
  workspaces:
    - name: maven-repo
      configMap:
        name: custom-maven-settings
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-tekton-pvc
      subPath: source
    - name: local-repo
      persistentvolumeclaim:
        claimName: maven-m2-pvc
