apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-tekton-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-m2-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
