apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clean-target-dir
spec:
  workspaces:
    - name: target-dir

  steps:
    - name: cleanup 
      image: ubuntu
      command:
        - rm 
      args:
        - -rf
        - "$(target-dir)/source/target"
---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-tekton-pipeline-cached
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-repo 
  tasks:
    - name: cleanup-target-folder
      taskRef:
        name: clean-target-dir 
      workspaces:
        - name: target-dir
          workspace: shared-workspace

    - name: clone-github-repo 
      taskRef:
        name: git-clone
      runAfter:
        - cleanup-target-folder 
      workspaces:
        - name: output 
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/tektutor/spring-ms.git
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "master"

    - name: start-maven-build 
      taskRef:
        name: maven
      runAfter:
        - clone-github-repo 
      params:
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -DskipTests
            - -Dmaven.repo.local="../$(shared-workspace)/m2"
            - clean
            - package
            - -X
      workspaces:
        - name: maven-settings 
          workspace: maven-repo
        - name: source 
          workspace: shared-workspace
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-tekton-pipeline-cached-run
spec:
  pipelineRef:
    name: maven-tekton-pipeline-cached
  taskRunSpecs:
    - pipelineTaskName: clone-github-repo 
      taskPodTemplate:
          securityContext:
            runAsNonRoot: false 
            runAsUser: 1001
            runAsGroup: 3000
            fsGroup: 2000
  workspaces:
    - name: maven-repo
      configMap:
        name: custom-maven-settings
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-tekton-pvc
      subPath: source
