apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-tekton-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-repo
  tasks:
    - name: clone-github-repo 
      taskRef:
        name: git-clone
      workspaces:
        - name: output 
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/tektutor/spring-ms.git
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "master"

    - name: start-maven-build 
      taskRef:
        name: maven
      runAfter:
        - clone-github-repo 
      params:
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
      workspaces:
        - name: maven-settings 
          workspace: maven-repo
        - name: source 
          workspace: shared-workspace
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-tekton-pipeline-run
spec:
  pipelineRef:
    name: maven-tekton-pipeline
  taskRunSpecs:
    - pipelineTaskName: clone-github-repo 
      taskPodTemplate:
          securityContext:
            runAsNonRoot: true 
            runAsUser: 1001
            runAsGroup: 3000
            fsGroup: 2000
  workspaces:
    - name: maven-repo
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-tekton-pvc
