apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-with-params
  namespace: jegan
spec:
  params:
    - name: message
      type: string
      description: You may send any greeting message to the task
      default: Default => Hello World
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - $(params.message) 
