apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-maven-task
spec:
  params:
    - name: contextDir
      default: .

    - name: mavenMirrorUrl
      default: https://repo.maven.apache.org/maven2/

  resources:
    inputs:
       name: source
       type: git

  steps:
    - name: build-sources
      image: docker.io/maven:3.6.3-openjdk-11-slim
      workingDir: "/workspace/source/$(inputs.params.contextDir)"
      command:
        - mvn
      args:
        - clean
        - package
      env:
        - name: user.home
          value: /home/tekton 
      volumeMounts:
        - name: myvol
          mountPath: /mnt
  securityContext:
    runAsUser: 0
    privileged: true
  volumes:
    - name: myvol
      emptyDir: {}
