apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-lister
spec:
  params:
    - name: contextDir
      default: quarkus
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: list-source-code
      image: busybox
      command: ["ls", "-ltr", "/workspace/source/$(inputs.params.contextDir)"]
