apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
  labels:
     tekton.dev/task: git-clone
spec:
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/tektutor/spring-ms.git
    - name: revision
      value: master
  workspaces:
    - name: output
      emptyDir: {} 
