apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-with-array-params
  namespace: jegan
spec:
  params:
    - name: message
      type: array
      default: [ "first", "second", "third" ] 
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - $(params.message) 
